# Generated by Django 4.2.3 on 2023-08-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='content',
            field=models.CharField(default='programing', max_length=100),
            preserve_default=False,
        ),
    ]
