# Generated by Django 4.2.3 on 2023-08-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
