# Generated by Django 4.2.3 on 2023-08-01 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_candidate_position_voter_votes_delete_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='positon',
            new_name='position',
        ),
        migrations.AddField(
            model_name='voter',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='otp_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voter',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(default='candidates/58028_4.jpg', upload_to='candidates'),
        ),
    ]
