# Generated by Django 4.2.3 on 2023-08-15 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='penulis',
        ),
    ]
